{% set name = "libml_dtypes-headers" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jax-ml/ml_dtypes/archive/v{{ version }}.tar.gz
  sha256: b85469201d6d086c16bc718e111bdb619396fab6d817f518dfd850c77ffc8de3

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __unix  # [unix]
    - __win  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/ml_dtypes/include/float8.h   # [unix]
    - test -f ${PREFIX}/include/ml_dtypes/include/mxfloat.h  # [unix]
    - test -f ${PREFIX}/include/ml_dtypes/include/intn.h     # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\float8.h (exit 1)   # [win]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\mxfloat.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\intn.h (exit 1)     # [win]


about:
  home: https://github.com/jax-ml/ml_dtypes
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
